#!/bin/bash
. colorecho
function cw(){
    cd ~/work/$1
}

function ct(){
    cd ~/temp/$1
}

function cs(){
    cd ~/su/$1
}

root=""
tag=""
function setd(){
    case $1 in
        "tag")
            tag=$2
            ;;
        "root")
            root=$2
            ;;
        *)
            echored "FAIL"
    esac
}
function setdir(){
    if [ $# -eq 1 ];then
        echogreen "set $1 directory to `pwd`"
        setd $1 `pwd`
        return
    fi
    if [ $# -eq 2 -a -d $2 ];then
        echogreen "set $1 directory to $2"
        setd $1 $2
    fi
}
function settag(){
    setdir tag $1
}

function setroot(){
    setdir root $1
}

function cdir(){
    if [ "X$2" == "X" ]
    then
        echored "$1 not set"
        echored "    use \"set$1 [directory]\" to set $1 directory"
        return
    fi
    cd $2
}

function cr(){
    cdir root $root
}

function ca(){
    cdir tag $tag
}
