#!/bin/bash

function printUsage(){
    echo "    usage:    "
    echo "          logcat [logcatfilename]"
    exit 1
}
echo $#
echo `[ $# -eq 0 ]`
if [ $# -eq 1 ];then
    adb logcat -c
    adb logcat | tee $1
elif [ $# -eq 0 ];then
     adb logcat -c 
     adb logcat | tee ~/temp/Logcat.txt
else
     printUsage
fi


