#!/bin/bash

function printUsage(){
    echo "    usage:    "
    echo "          logcat [logcatfilename]"
    exit 1
}
function startlog(){
    adb $1 wait-for-device
    adb $1 logcat -c
    adb $1 logcat | tee $logfile
}

logfile=~/temp/logcat.txt
arg=""

while [ $# > 0 ] 
do
    case $1 in
        "-s")
            arg="-s #2"
            break
            ;;
        *)
            shift
            ;;
    esac
done
startlog $arg
